#!/bin/bash
# Script that updates the trash-updater script and then updates sonarr and radarr with profiles and custom formats from trash-guides (https://trash-guides.info).
# Script location: https://github.com/rcdailey/trash-updater

# Change cd command to location where you would like the script to save to
cd /mnt/user/appdata/radarr/trashscript && wget -O trash.zip https://github.com/rcdailey/trash-updater/releases/latest/download/trash-linux-x64.zip && unzip -o trash.zip && rm trash.zip && chmod u+rx trash && trash sonarr && trash radarr
